export {default as Home} from '../pages/Home'
export {default as Projects} from '../pages/Projects'
export {default as Dashboard} from '../pages/Dashboard'
export {default as About} from '../pages/About'
export {default as Skills} from './Skills'
export {default as Contact} from './Contact'
export {default as Hirigns} from './Hirigns'
export {default as PageNotFound} from '../pages/PageNotFound'